[workspace]
members = [
    "runtime",
    "gvmkit",
]

[patch.crates-io]
ya-runtime-sdk = { git = "https://github.com/golemfactory/ya-runtime-sdk.git", rev = "f6b8c6a5ede9a36d73ebb58be343a53c9231ea34" }
